layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Ruby
    web_url: https://github.com/ruby/ruby
    image_url: https://avatars2.githubusercontent.com/u/210414?s=200&v=4

  - name: Ruby on Rails
    web_url: https://github.com/rails/rails
    image_url: https://rubyonrails.org/images/rails-logo.svg

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
  
theme: jekyll-theme-cayman